INSERT INTO verbs(
    infinitive,
    present_participle,
    past_participle,
    indicative_present_yo,
    indicative_present_tu,
    indicative_present_usted,
    indicative_present_nosotros,
    indicative_present_vosotros,
    indicative_present_ustedes,
    indicative_preterite_yo,
    indicative_preterite_tu,
    indicative_preterite_usted,
    indicative_preterite_nosotros,
    indicative_preterite_vosotros,
    indicative_preterite_ustedes,
    indicative_imperfect_yo,
    indicative_imperfect_tu,
    indicative_imperfect_usted,
    indicative_imperfect_nosotros,
    indicative_imperfect_vosotros,
    indicative_imperfect_ustedes,
    indicative_conditional_yo,
    indicative_conditional_tu,
    indicative_conditional_usted,
    indicative_conditional_nosotros,
    indicative_conditional_vosotros,
    indicative_conditional_ustedes,
    indicative_future_yo,
    indicative_future_tu,
    indicative_future_usted,
    indicative_future_nosotros,
    indicative_future_vosotros,
    indicative_future_ustedes,
    subjunctive_present_yo,
    subjunctive_present_tu,
    subjunctive_present_usted,
    subjunctive_present_nosotros,
    subjunctive_present_vosotros,
    subjunctive_present_ustedes,
    subjunctive_imperfect_1_yo,
    subjunctive_imperfect_1_tu,
    subjunctive_imperfect_1_usted,
    subjunctive_imperfect_1_nosotros,
    subjunctive_imperfect_1_vosotros,
    subjunctive_imperfect_1_ustedes,
    subjunctive_imperfect_2_yo,
    subjunctive_imperfect_2_tu,
    subjunctive_imperfect_2_usted,
    subjunctive_imperfect_2_nosotros,
    subjunctive_imperfect_2_vosotros,
    subjunctive_imperfect_2_ustedes,
    subjunctive_future_yo,
    subjunctive_future_tu,
    subjunctive_future_usted,
    subjunctive_future_nosotros,
    subjunctive_future_vosotros,
    subjunctive_future_ustedes,
    imperative_affirmative_tu,
    imperative_affirmative_usted,
    imperative_affirmative_nosotros,
    imperative_affirmative_vosotros,
    imperative_affirmative_ustedes,
    imperative_negative_tu,
    imperative_negative_usted,
    imperative_negative_nosotros,
    imperative_negative_vosotros,
    imperative_negative_ustedes,
    progressive_present_yo,
    progressive_present_tu,
    progressive_present_usted,
    progressive_present_nosotros,
    progressive_present_vosotros,
    progressive_present_ustedes,
    progressive_preterite_yo,
    progressive_preterite_tu,
    progressive_preterite_usted,
    progressive_preterite_nosotros,
    progressive_preterite_vosotros,
    progressive_preterite_ustedes,
    progressive_imperfect_yo,
    progressive_imperfect_tu,
    progressive_imperfect_usted,
    progressive_imperfect_nosotros,
    progressive_imperfect_vosotros,
    progressive_imperfect_ustedes,
    progressive_conditional_yo,
    progressive_conditional_tu,
    progressive_conditional_usted,
    progressive_conditional_nosotros,
    progressive_conditional_vosotros,
    progressive_conditional_ustedes,
    progressive_future_yo,
    progressive_future_tu,
    progressive_future_usted,
    progressive_future_nosotros,
    progressive_future_vosotros,
    progressive_future_ustedes,
    perfect_present_yo,
    perfect_present_tu,
    perfect_present_usted,
    perfect_present_nosotros,
    perfect_present_vosotros,
    perfect_present_ustedes,
    perfect_preterite_yo,
    perfect_preterite_tu,
    perfect_preterite_usted,
    perfect_preterite_nosotros,
    perfect_preterite_vosotros,
    perfect_preterite_ustedes,
    perfect_past_yo,
    perfect_past_tu,
    perfect_past_usted,
    perfect_past_nosotros,
    perfect_past_vosotros,
    perfect_past_ustedes,
    perfect_conditional_yo,
    perfect_conditional_tu,
    perfect_conditional_usted,
    perfect_conditional_nosotros,
    perfect_conditional_vosotros,
    perfect_conditional_ustedes,
    perfect_future_yo,
    perfect_future_tu,
    perfect_future_usted,
    perfect_future_nosotros,
    perfect_future_vosotros,
    perfect_future_ustedes,
    perfect_subjunctive_present_yo,
    perfect_subjunctive_present_tu,
    perfect_subjunctive_present_usted,
    perfect_subjunctive_present_nosotros,
    perfect_subjunctive_present_vosotros,
    perfect_subjunctive_present_ustedes,
    perfect_subjunctive_past_1_yo,
    perfect_subjunctive_past_1_tu,
    perfect_subjunctive_past_1_usted,
    perfect_subjunctive_past_1_nosotros,
    perfect_subjunctive_past_1_vosotros,
    perfect_subjunctive_past_1_ustedes,
    perfect_subjunctive_past_2_yo,
    perfect_subjunctive_past_2_tu,
    perfect_subjunctive_past_2_usted,
    perfect_subjunctive_past_2_nosotros,
    perfect_subjunctive_past_2_vosotros,
    perfect_subjunctive_past_2_ustedes,
    perfect_subjunctive_future_yo,
    perfect_subjunctive_future_tu,
    perfect_subjunctive_future_usted,
    perfect_subjunctive_future_nosotros,
    perfect_subjunctive_future_vosotros,
    perfect_subjunctive_future_ustedes
) VALUES (
    'ganar',
    'ganando',
    'ganado',
    'gano',
    'ganas',
    'gana',
    'ganamos',
    'ganáis',
    'ganan',
    'gané',
    'ganaste',
    'ganó',
    'ganamos',
    'ganasteis',
    'ganaron',
    'ganaba',
    'ganabas',
    'ganaba',
    'ganábamos',
    'ganabais',
    'ganaban',
    'ganaría',
    'ganarías',
    'ganaría',
    'ganaríamos',
    'ganaríais',
    'ganarían',
    'ganaré',
    'ganarás',
    'ganará',
    'ganaremos',
    'ganaréis',
    'ganarán',
    'gane',
    'ganes',
    'gane',
    'ganemos',
    'ganéis',
    'ganen',
    'ganara',
    'ganaras',
    'ganara',
    'ganáramos',
    'ganarais',
    'ganaran',
    'ganase',
    'ganases',
    'ganase',
    'ganásemos',
    'ganaseis',
    'ganasen',
    'ganare',
    'ganares',
    'ganare',
    'ganáremos',
    'ganareis',
    'ganaren',
    'gana',
    'gane',
    'ganemos',
    'ganad',
    'ganen',
    'no ganes',
    'no gane',
    'no ganemos',
    'no ganéis',
    'no ganen',
    'estoy ganando',
    'estás ganando',
    'está ganando',
    'estamos ganando',
    'estáis ganando',
    'están ganando',
    'estuve ganando',
    'estuviste ganando',
    'estuvo ganando',
    'estuvimos ganando',
    'estuvisteis ganando',
    'estuvieron ganando',
    'estaba ganando',
    'estabas ganando',
    'estaba ganando',
    'estábamos ganando',
    'estabais ganando',
    'estaban ganando',
    'estaría ganando',
    'estarías ganando',
    'estaría ganando',
    'estaríamos ganando',
    'estaríais ganando',
    'estarían ganando',
    'estaré ganando',
    'estarás ganando',
    'estará ganando',
    'estaremos ganando',
    'estaréis ganando',
    'estarán ganando',
    'he ganado',
    'has ganado',
    'ha ganado',
    'hemos ganado',
    'habéis ganado',
    'han ganado',
    'hube ganado',
    'hubiste ganado',
    'hubo ganado',
    'hubimos ganado',
    'hubisteis ganado',
    'hubieron ganado',
    'había ganado',
    'habías ganado',
    'había ganado',
    'habíamos ganado',
    'habíais ganado',
    'habían ganado',
    'habría ganado',
    'habrías ganado',
    'habría ganado',
    'habríamos ganado',
    'habríais ganado',
    'habrían ganado',
    'habré ganado',
    'habrás ganado',
    'habrá ganado',
    'habremos ganado',
    'habréis ganado',
    'habrán ganado',
    'haya ganado',
    'hayas ganado',
    'haya ganado',
    'hayamos ganado',
    'hayáis ganado',
    'hayan ganado',
    'hubiera ganado',
    'hubieras ganado',
    'hubiera ganado',
    'hubiéramos ganado',
    'hubierais ganado',
    'hubieran ganado',
    'hubiese ganado',
    'hubieses ganado',
    'hubiese ganado',
    'hubiésemos ganado',
    'hubieseis ganado',
    'hubiesen ganado',
    'hubiere ganado',
    'hubieres ganado',
    'hubiere ganado',
    'hubiéremos ganado',
    'hubiereis ganado',
    'hubieren ganado'
);